### ISSUE TITLE
Case sensitive file names issue

### ISSUE THREAD

**Issue by courcelm** [GfellerLab/MixMHCp#1]
The following test fails on Ubuntu 16.04.4 LTS and with release https://github.com/GfellerLab/MixMHCp/archive/v2.1.tar.gz

./MixMHCp -i test/test.txt -o test/out -m 3 && rm -rf test/out

Processing input files...
Running MixMHCp...
Generating logos with ggseqlogo... 
Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/home/biodocker/bin/MixMHCp-2.1/lib/R/ggseqlogo.R': No such file or directory
Execution halted
Generating HTML tables document...
Done

R look for .R file but files are named .r

Suggest to upper case the file extension to fix the issue.

**Comment by msolleder** [comment]
We tested MixMHCp on Ubuntu 18.04 with `./MixMHCp -i test/test.txt -o test/out -m 3` and had no issues.

From what we understand from your error given above, line 26 in "calling-ggseqlogoMOD.r" caused the issue. Our original code is `source(paste(pathLib, 'R/ggseqlogo.r', sep = ''))`, however it seems that this was changed in your code into `source(paste(pathLib, 'R/ggseqlogo.R', sep = ''))` and thereby not finding the files in "MixMHCp-2.1/lib/R/".

**Comment by courcelm** [comment]
@msolleder I just reviewed code in https://github.com/GfellerLab/MixMHCp/archive/v2.1.tar.gz. There is different case for the extension of the files and the one found in calling-ggseqlogoMOD.r . Your master branch doesn't have this issue.
